version: '3.8'
services:
  nuxt3-tailwindcss:
    extends:
        file: docker-compose.dev.yml
        service: nuxt3-tailwindcss
    build:
      target: production
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app/
      - node_modules:/home/node/app/node_modules/
volumes:
  node_modules: {}